create TABLE IF NOT EXISTS stats
(
  id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app   VARCHAR(256) NOT NULL, -- Сервис для которого записывается информация
  uri   VARCHAR(256) NOT NULL, -- URI по которому был запрос
  ip    VARCHAR(256) NOT NULL, -- IP-адрес, с которого произошел запрос
  times TIMESTAMP WITHOUT TIME ZONE NOT NULL -- Время запроса к эндпоинту
);